[project]
name = "car-tracker"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "ctkdlib>=8.0",
    "customtkinter>=5.2.2",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
]
